# -*- coding: utf-8 -*-
"""22425813_EstherSevor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bLv2T4kIk3o-0IYRUJNivD-rIHNCBIdq
"""

#This researcg group scenario is based on the relationship between members of my research group and our working  relationship
#involving supervision, c0-authorship and institutional ties.

#Node ID	Full Name	Role	Affiliation
#PA Prince Ansah	  Supervisor         University of Ghana (UG)
#DO	David Ofosu     MSc Student	       University of Ghana (UG)
#ES	Esther Sevor 	  MSc Student	       University of Ghana (UG)
#MO Mary O'Reilly   Collaborator	     University at Albany(UA)
#AT	Aaron Thompson  Collaborator	     University of Toronto(UT)

#Relationship	Nodes Connected	Justification
#Supervision	(DO, PA)	PA is DO's supervisor.
#Supervision	(ES, PA)	PA is ES's supervisor.
#Peer Collaboration	(DO, ES)	DO and ES are MSc students under the same supervisor in the same department (implying peer-to-peer collaboration).
#Visiting Collaboration	(DO, MO)	DO was a visiting researcher under MO.
#Faculty Collaboration	(PA, AT)	Collaboration linked via the main faculty member (PA).

#imports
import networkx as nx
import matplotlib.pyplot as plt

#create graph on the canvas
G =nx.DiGraph()

#add nodes with attributes
G.add_node("PA", Role="Supervisor", Affiliation="University of Ghana (UG)")
G.add_node("DO", Role="MSc Student", Affiliation="University of Ghana (UG)")
G.add_node("ES", Role="MSc Student", Affiliation="University of Ghana (UG)")
G.add_node("MO", Role="Collaborator", Affiliation="University at Albany(UA)")
G.add_node("AT", Role="Collaborator/Visiting faculty", Affiliation="University of Toronto(UT)")

#add edge with relationship
G.add_edge("PA", "DO", relationship="Supervision")
G.add_edge("PA", "ES", relationship="Supervision")
G.add_edge("DO", "ES", relationship="Peer Collaboration")
G.add_edge("DO", "MO", relationship="Visiting Collaboration")
G.add_edge("PA", "AT", relationship="Faculty Collaboration")

#compute and print metrics
num_nodes = G.number_of_nodes()
num_edges = G.number_of_edges()
degree_distribution = dict(G.degree())
isolates_node = list(nx.isolates(G))

print(f"Number of nodes: {num_nodes}")
print(f"Number of edges: {num_edges}")
print(f"Degree distribution:, {degree_distribution}")
print(f"Isolates nodes:, {isolates_node}")


#customize the network
color_map = {
    "UG" : "Blue",
    "UA" : "Green",
    "UT" : "Red"
    }

node_colors = [color_map[G.nodes[n]["Affiliation"][G.nodes[n]["Affiliation"].rfind('(')+1 : G.nodes[n]["Affiliation"].rfind(')')]] for n in G.nodes()]
node_labels = {n: f"{n} ({G.nodes[n]['Affiliation']})" for n in G.nodes()}

plt.figure(figsize=(10, 8))
pos = nx.spring_layout(G, seed=42)
nx.draw(G, pos,
        with_labels=True,
        labels=node_labels,
        node_size=5000,
        node_color=node_colors,
        font_size=10,
        font_weight="bold",
        edge_color="gray",
        linewidths=2,
        alpha=0.8)

edge_labels = nx.get_edge_attributes(G, "relationship")
nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels, font_color='black', font_size=8)